/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compilador1;

import METODOS_GRAMATICA.PCK_CLASS;
import METODO_CODIGO.PROC_CODIGO;
import OBJETOS_TABLA.ERROR;
import OBJETOS_TABLA.OBJETO_T;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author LMC Alumno
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PRINCIPAL() {
        initComponents();
        Modelo1.addColumn("ID");
        Modelo1.addColumn("LEXEMA");
        Modelo1.addColumn("TOKEN");
        TABLA.setModel(Modelo1);
        Modelo2.addColumn("LINEA");
        Modelo2.addColumn("TIPO");
        Modelo2.addColumn("ERROR");
        Modelo2.addColumn("DESCRIPCION");
        TABLA2.setModel(Modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TXTCODIGODEPURADO = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTAREAINPUT = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnANALIZAR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TABLA2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTCODIGODEPURADO.setColumns(20);
        TXTCODIGODEPURADO.setRows(5);
        jScrollPane1.setViewportView(TXTCODIGODEPURADO);

        TXTAREAINPUT.setColumns(20);
        TXTAREAINPUT.setRows(5);
        TXTAREAINPUT.setText("package x;\npublic class Student {\n  int a = 2 * 10 + (60 / 30 * 23);\n  public int VALIDAR(int a, int b){\n\n }\n}");
        jScrollPane2.setViewportView(TXTAREAINPUT);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("INPUT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CODIGO DEPURADO");

        btnANALIZAR.setText("ANALIZAR");
        btnANALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnANALIZARActionPerformed(evt);
            }
        });

        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });

        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "LEXEMA", "TOKEN"
            }
        ));
        jScrollPane3.setViewportView(TABLA);
        if (TABLA.getColumnModel().getColumnCount() > 0) {
            TABLA.getColumnModel().getColumn(0).setResizable(false);
            TABLA.getColumnModel().getColumn(1).setResizable(false);
            TABLA.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("TABLA DE SIMBOLOS");

        TABLA2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TABLA2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(313, 313, 313)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnANALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BTNBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnANALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel Modelo1 = new DefaultTableModel();
    DefaultTableModel Modelo2 = new DefaultTableModel();
    public ArrayList<ERROR> erroresF = new ArrayList<ERROR>();


    private void btnANALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnANALIZARActionPerformed
        PROC_CODIGO A = new PROC_CODIGO();
        PCK_CLASS GRAMATICA = new PCK_CLASS();
        try {
            TABLA.setModel(Modelo1);
            String Codigo = TXTAREAINPUT.getText();
            String CodigoDepu = A.depurarCodigo(Codigo);
            //TXTCODIGODEPURADO.setText(A.Agregar(A.getEspacios(), CodigoDepu));
            TXTCODIGODEPURADO.setText(CodigoDepu);
            String[] b = A.DIVIDIRCODIGO(A.depurarCodigo(Codigo));
            ArrayList<String> c = A.DIVIDIRFINAL(b);
            ArrayList<OBJETO_T> LISTAT = A.CLASIFICAR(c);
            LLENARTABLA(LISTAT);
            LLENARTABLAE(A.getErrores());
            LLENARTABLAE(GRAMATICA.VALIDAR_PCK(LISTAT));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e);
        }

    }//GEN-LAST:event_btnANALIZARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            JFileChooser BuscadorA = new JFileChooser();
            BuscadorA.showOpenDialog(null);
            File archivo = new File(BuscadorA.getSelectedFile().getAbsolutePath());
            if (!archivo.equals(null)) {
                try {
                    String Archivo = new String(Files.readAllBytes(archivo.toPath()));
                    TXTAREAINPUT.setText(Archivo);
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "NO SE ENCONTRO EL ARCHIVO" + ex);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "ERROR: " + ex);
                }
            } else {

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed
    public void LLENARTABLA(ArrayList<OBJETO_T> LISTAT) {
        int id = 1;
        for (OBJETO_T O : LISTAT) {
            String ID = String.valueOf(id);
            if (O.getTOKEN() == "IDU") {

                String Objeto[] = {ID, O.getLexema(), O.getTOKEN()};
                id++;
                Modelo1.addRow(Objeto);

            } else {
                String Objeto2[] = {null, O.getLexema(), O.getTOKEN()};
                Modelo1.addRow(Objeto2);
            }
        }
    }

    public void LLENARTABLAE(ArrayList<ERROR> LISTAE) {
        if (!LISTAE.isEmpty()) {
            for (ERROR O : LISTAE) {
                String Objeto[] = {O.getLinea(), O.getTIPO(), O.getError(), O.getDescripcion()};
                Modelo2.addRow(Objeto);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JTable TABLA;
    private javax.swing.JTable TABLA2;
    private javax.swing.JTextArea TXTAREAINPUT;
    private javax.swing.JTextArea TXTCODIGODEPURADO;
    private javax.swing.JButton btnANALIZAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
